### PR TITLE
Adds press enter to submit functionality

### LINKED ISSUE #5: To submit an address, allow user to just press enter
Currently they must press the "Submit" button

### PR DESCRIPTION
**Pull request by pulkonet**
fixes #5 
Please label this as hacktoberfest

### CODE REVIEW

**Comment by zmon** [comment]
Tried it in Chrom and did not work as expected.  Action I took:

1. Typed "210 W19" in the Address field
2. Selected "210 W 19TH TER FL 1, KANSAS CITY, MO" by clicking on it
3. Press Enter - cleared Address field.

**Comment by pulkonet** [comment]
I'll check and revert.

**Comment by pulkonet** [comment]
@zmon Please check and revert.

**Comment by pulkonet** [comment]
@zmon  please check and revert

**Comment by zmon** [comment]
@pulkonet thank you, you might look at "Add spinner or progress bar when waiting for GIS API to return data #10"

**Pull request merged**
